### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lboeman** [RisingStack/auth0-ts-vue-example#1]
Hello!
I want to say thanks for creating this example, your blog post was immensely helpful in getting auth0 set up with Vue and Typescript.

While the blog does seem to encourage some copying and pasting, I'm wary of using this code without explicit consent. It would be great if a license could be added to the repo to clear up what is fair use.

**Comment by Shadowbeetle** [comment]
Hi!

I'm glad you found it useful! I've added a license, so you can copy-paste freely, thanks for pointing that out!
